version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: todo-list-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=todolist
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
